/** Do not edit! This file is auto-generated. */

import { Pepicon } from '../types'

export const synonyms: { [name in Pepicon]: string[] } = {
  'battery': ['charge'],
  'calculator': ['calculate'],
  'camera': ['record', 'video'],
  'monitor2': ['computer', 'desktop', 'screen'],
  'monitor': ['computer', 'desktop', 'screen'],
  'photo-camera': ['photography', 'shutter', 'picture'],
  'printer': ['pdf'],
  'smartphone-notch': ['iphone', 'mobile-phone', 'cell-phone', 'gsm'],
  'smartphone2': ['iphone', 'mobile-phone', 'cell-phone', 'gsm'],
  'smartphone': ['iphone', 'mobile-phone', 'cell-phone', 'gsm'],
  'television': ['tv', 'telly'],
  'can': ['pepsi', 'soft-drink', 'fizzy', 'cola', 'cold-drink', 'refresher', 'juice'],
  'coctail': ['alcohol', 'tropical'],
  'cup': ['coffee', 'hot-drink'],
  'hamburger': ['fast-food'],
  'knive-fork': ['eat', 'cutlery'],
  'soft-drink': ['cold-drink', 'refresher', 'juice'],
  'credit-card': ['master-card', 'visa', 'cashless', 'payment', 'checkout'],
  'dress': ['one-piece', 'clothing', 'gown', 'frock', 'garment'],
  'key': ['lock', 'unlock', 'encrypt', 'decrypt', 'safe', 'secret', 'solution', 'answer'],
  'lock-closed': ['lock', 'encrypt'],
  'lock-open': ['unlock', 'decrypt'],
  'magnet': ['attraction', 'repel', 'repulsion'],
  'pill': ['medicine', 'capsule', 'pellet', 'doctor', 'sick', 'disease', 'cure', 'drugs'],
  'scissors': ['cut', 'hair', 'clippers', 'shears', 'trimmer', 'barber', 'stylist', 'beauty-parlor', 'coiffeuse', 'coiffeur'],
  'syringe': ['hypodermic', 'injection', 'vaccine', 'vaccination', 'doctor', 'sick', 'disease', 'cure', 'drugs'],
  't-shirt': ['clothing'],
  'umbrella': ['parasol', 'rain'],
  'book': ['read', 'bookmark'],
  'cart': ['shopping', 'payout', 'commerce', 'transaction', 'buy', 'purchase'],
  'controller': ['video-game', 'console-1'],
  'controller': ['video-game', 'console'],
  'film-frame': ['picture', 'movie', 'roll', 'feature', 'tv', 'television', 'programme', 'motion-picture', 'animation', 'flick', 'cinema'],
  'paint-pallet': ['painter', 'art'],
  'building': ['office', 'sky-scraper', 'business', 'work', 'workplace', 'headquarters', 'enterprise', 'company', 'firm', 'bureau', 'agency', 'corporation'],
  'flag': ['banner', 'country', 'important', 'pin'],
  'house': ['home', 'residence'],
  'internet': ['web', 'cyber', 'remote'],
  'pinpoint-filled': ['location-marker', 'pin', 'position', 'map', 'here', 'where'],
  'pinpoint-off-filled': ['location-marker-off', 'pin', 'position', 'map', 'here', 'where'],
  'pinpoint-off': ['location-marker-off', 'pin', 'position', 'map', 'here', 'where'],
  'pinpoint': ['location-marker', 'pin', 'position', 'map', 'here', 'where'],
  'electricity': ['thunder', 'lightning'],
  'flower-bud': ['daisy'],
  'flower': ['tulip'],
  'moon-filled': ['dark-mode', 'lights-out'],
  'moon': ['dark-mode', 'night', 'lights-out'],
  'star-filled': ['favourite', 'favorite', 'rate', 'rating', 'score', 'flag'],
  'star': ['favourite', 'favorite', 'rate', 'rating', 'score', 'flag'],
  'sun-filled': ['light-mode', 'lights-on', 'brightness'],
  'sun': ['light-mode', 'day', 'lights-on', 'brightness'],
  'circle-filled': ['bullet', 'ball'],
  'circle': ['bullet', 'ball'],
  'division': ['divide'],
  'minus': ['dash', 'hyphen', 'line'],
  'plus': ['cross', 'add', 'new'],
  'square-filled': [],
  'square': [],
  'times': ['cross', 'x', 'wrong', 'close', 'stop'],
  'triangle-down-filled': ['arrow-down'],
  'triangle-down': ['arrow-down'],
  'triangle-left-filled': ['arrow-left'],
  'triangle-left': ['arrow-left'],
  'triangle-right-filled': ['arrow-right'],
  'triangle-right': ['arrow-right'],
  'triangle-up-filled': ['arrow-up'],
  'triangle-up': ['arrow-up'],
  'gift': ['present', 'surprise', 'give'],
  'heart': ['love', 'like'],
  'letter': ['email', 'post', 'inbox'],
  'person-filled': ['human', 'man', 'someone', 'unknown', 'identity', 'profile', 'you'],
  'person': ['human', 'man', 'someone', 'unknown', 'identity', 'profile', 'you'],
  'phone': ['call', 'talk', 'telephone'],
  'send': ['email', 'paper-plane'],
  'share-android': ['forward', 'connect'],
  'share-ios': ['forward', 'connect'],
  'text-bubble': ['message', 'chat', 'say', 'typing'],
  'bell-off': ['no-notification', 'no-attention', 'quiet', 'silent', 'no-alert'],
  'bell': ['notification', 'attention', 'alert'],
  'headphone': ['headset', 'earphone', 'music', 'listen', 'anc'],
  'microphone': ['record', 'voice', 'radio'],
  'music-note-double': ['score', 'solfege', 'song'],
  'music-note-single': ['score', 'solfege', 'song'],
  'speaker-high': ['high-volume', 'loud'],
  'speaker-low': ['low-volume', 'quiet'],
  'speaker-off': ['no-volume', 'silent'],
  'bookmark-filled': ['flag', 'clip'],
  'bookmark': ['flag', 'clip'],
  'clipboard': ['copy'],
  'exclamation-filled': ['bang', 'exclamation-mark', 'exclamation-point', 'shriek', 'pling', 'note-of-admiration', 'warning', 'danger', 'error'],
  'exclamation': ['bang', 'exclamation-mark', 'exclamation-point', 'shriek', 'pling', 'note-of-admiration', 'warning', 'danger', 'error'],
  'info-filled': ['information', 'help', 'hint', 'guide'],
  'info': ['information', 'help', 'hint', 'guide'],
  'pen': ['edit', 'write', 'pencil', 'draw'],
  'calendar': ['date', 'when'],
  'clock': ['time', 'timer', 'countdown'],
  'airplane': ['aeroplane', 'fly', 'travel', 'vacation', 'trip', 'flight', 'airport'],
  'bicycle': ['bike'],
  'car': ['automobile', 'drive'],
  'map': ['location', 'directions'],
  'motorcycle': ['bike'],
  'taxi': ['cab'],
  'train': ['tube', 'metro'],
  'truck': ['heavy-goods-vehicle', 'juggernaut', 'van', 'pickup', 'lorry', 'move', 'wares', 'deliver', 'haul', 'distribution', 'delivery'],
  'angle-down': ['arrow-down', 'chevron-down', 'bracket-down', 'to-bottom', 'go-down'],
  'angle-left': ['arrow-left', 'chevron-left', 'bracket-left', 'bracket-open', 'opening-bracket', 'less-than', 'back'],
  'angle-right': ['arrow-right', 'chevron-right', 'bracket-right', 'bracket-close', 'closing-bracket', 'greater-than', 'more-than', 'forward'],
  'angle-up': ['arrow-up', 'chevron-up', 'bracket-up', 'to-top', 'go-up'],
  'bluetooth': [],
  'checkmark': ['check', 'toggle', 'tick', 'ok', 'confirmed'],
  'cloud-down-filled': ['download', 'storage', 'retrieve', 'fetch', 'local', 'load'],
  'cloud-down': ['download', 'storage', 'retrieve', 'fetch', 'local', 'load'],
  'cloud-filled': ['upload', 'online', 'storage', 'save'],
  'cloud-up-filled': ['upload', 'storage', 'save'],
  'cloud-up': ['upload', 'storage', 'save'],
  'cloud': ['upload', 'online', 'storage', 'save'],
  'color-picker': [],
  'contract': ['shrink', 'close', 'zoom-out', 'minimize'],
  'dots-x': ['dots-horizontal', 'more', 'details', 'menu'],
  'dots-y': ['dots-vertical', 'more', 'details', 'menu'],
  'duplicate': ['copy'],
  'expand': ['fullscreen', 'open', 'zoom-in', 'maximize'],
  'eye-closed': ['password-hidden', 'invisible', 'hide', 'secret', 'asleep'],
  'eye-off': ['password-hidden', 'invisible', 'hide', 'secret', 'not-allowed', 'no-access'],
  'eye': ['password-visible', 'see', 'watch', 'awake'],
  'file': ['document', 'record', 'note', 'data', 'archive'],
  'folder': ['container', 'binder', 'files', 'archive', 'save', 'record', 'keep'],
  'gear': ['settings', 'cogwheel', 'configuration', 'mechanical', 'machinery'],
  'grab': ['handle', 'move', 'drag'],
  'loop-minus': ['zoom-out', 'magnify-out', 'farther', 'further'],
  'loop-plus': ['zoom-in', 'magnify-in', 'closer'],
  'loop': ['zoom', 'magnify', 'detective'],
  'open': ['link', 'new-tab', 'external', 'go'],
  'power': ['turn-off', 'shut-down'],
  'refresh': ['reload', 'fetch', 'twist'],
  'reload': ['refresh', 'turn', 'start-over', 'back'],
  'tool': ['wrench', 'hardware', 'fix', 'repair', 'bolt'],
  'trash': ['delete', 'remove', 'dispense', 'trashcan', 'can', 'garbage'],
  'wifi': ['internet', 'reception', 'connection', 'sonic', 'waves'],
}
