/** Do not edit! This file is auto-generated. */

import { PepiconName } from '../types'

export const synonyms: { [name in PepiconName]: string[] } = {
  'airplane': ['arrow-down', 'chevron-down', 'bracket-down', 'to-bottom', 'go-down'],
  'airplane-circle': [],
  'airplane-circle-filled': [],
  'airplane-circle-off': [],
  'airplane-off': [],
  'alarm': ['arrow-left', 'chevron-left', 'bracket-left', 'bracket-open', 'opening-bracket', 'less-than', 'back', 'previous', 'before'],
  'alarm-circle': [],
  'alarm-circle-filled': [],
  'alarm-circle-off': [],
  'alarm-off': [],
  'angle-down': ['arrow-right', 'chevron-right', 'bracket-right', 'bracket-close', 'closing-bracket', 'greater-than', 'more-than', 'next', 'after', 'forward'],
  'angle-down-circle': [],
  'angle-down-circle-filled': [],
  'angle-down-circle-off': [],
  'angle-down-off': [],
  'angle-left': ['arrow-up', 'chevron-up', 'bracket-up', 'to-top', 'go-up'],
  'angle-left-circle': [],
  'angle-left-circle-filled': [],
  'angle-left-circle-off': [],
  'angle-left-off': [],
  'angle-right': ['south-west', 'point', 'bolt', 'dart', 'compass', 'direction', 'needle', 'orientation'],
  'angle-right-circle': [],
  'angle-right-circle-filled': [],
  'angle-right-circle-off': [],
  'angle-right-off': [],
  'angle-up': ['south-east', 'point', 'bolt', 'dart', 'compass', 'direction', 'needle', 'orientation'],
  'angle-up-circle': [],
  'angle-up-circle-filled': [],
  'angle-up-circle-off': [],
  'angle-up-off': [],
  'arrow-down': ['south', 'point', 'bolt', 'dart', 'compass', 'direction', 'needle', 'orientation', 'to-bottom', 'go-down'],
  'arrow-down-circle': [],
  'arrow-down-circle-filled': [],
  'arrow-down-circle-off': [],
  'arrow-down-left': [],
  'arrow-down-left-circle': ['west', 'point', 'bolt', 'dart', 'compass', 'direction', 'needle', 'orientation', 'previous', 'back', 'before'],
  'arrow-down-left-circle-filled': [],
  'arrow-down-left-circle-off': [],
  'arrow-down-left-off': [],
  'arrow-down-off': [],
  'arrow-down-right': ['east', 'point', 'bolt', 'dart', 'compass', 'direction', 'needle', 'orientation', 'next', 'after', '', 'next', 'after', 'forward'],
  'arrow-down-right-circle': [],
  'arrow-down-right-circle-filled': [],
  'arrow-down-right-circle-off': [],
  'arrow-down-right-off': [],
  'arrow-left': ['reload', 'refresh', 'turn', 'start-over', 'back', 'around', 'spin'],
  'arrow-left-circle': [],
  'arrow-left-circle-filled': [],
  'arrow-left-circle-off': [],
  'arrow-left-off': [],
  'arrow-right': ['north-west', 'point', 'bolt', 'dart', 'compass', 'direction', 'needle', 'orientation'],
  'arrow-right-circle': [],
  'arrow-right-circle-filled': [],
  'arrow-right-circle-off': [],
  'arrow-right-off': [],
  'arrow-spin': ['north-east', 'point', 'bolt', 'dart', 'compass', 'direction', 'needle', 'orientation'],
  'arrow-spin-circle': [],
  'arrow-spin-circle-filled': [],
  'arrow-spin-circle-off': [],
  'arrow-spin-off': [],
  'arrow-up': ['north', 'point', 'bolt', 'dart', 'compass', 'direction', 'needle', 'orientation', 'to-top', 'go-up'],
  'arrow-up-circle': [],
  'arrow-up-circle-filled': [],
  'arrow-up-circle-off': [],
  'arrow-up-left': [],
  'arrow-up-left-circle': ['refresh', 'reload', 'fetch', 'twist', 'turn', 'go-round', 'spin'],
  'arrow-up-left-circle-filled': [],
  'arrow-up-left-circle-off': [],
  'arrow-up-left-off': [],
  'arrow-up-off': [],
  'arrow-up-right': ['shrink', 'close', 'zoom-out', 'minimize'],
  'arrow-up-right-circle': [],
  'arrow-up-right-circle-filled': [],
  'arrow-up-right-circle-off': [],
  'arrow-up-right-off': [],
  'arrows-spin': ['reply', 'new-line', 'line-break', 'enter'],
  'arrows-spin-circle': [],
  'arrows-spin-circle-filled': [],
  'arrows-spin-circle-off': [],
  'arrows-spin-off': [],
  'bank': ['sort', 'order', 'arrows', 'arrange', 'organise', 'organize', 'rate', 'tabulate'],
  'bank-circle': [],
  'bank-circle-filled': [],
  'bank-circle-off': [],
  'bank-off': [],
  'battery': ['fullscreen', 'open', 'zoom-in', 'maximize'],
  'battery-circle': [],
  'battery-circle-filled': [],
  'battery-circle-off': [],
  'battery-off': [],
  'bell': ['x-axis', 'width', 'drag', 'left-right', 'expand', 'grow', 'stretch'],
  'bell-circle': [],
  'bell-circle-filled': [],
  'bell-circle-off': [],
  'bell-off': [],
  'bicycle': ['y-axis', 'height', 'drag', 'up-down', 'expand', 'grow', 'stretch'],
  'bicycle-circle': [],
  'bicycle-circle-filled': [],
  'bicycle-circle-off': [],
  'bicycle-off': [],
  'bluetooth': ['charge'],
  'bluetooth-circle': [],
  'bluetooth-circle-filled': [],
  'bluetooth-circle-off': [],
  'bluetooth-off': [],
  'book': ['calculate'],
  'book-circle': [],
  'book-circle-filled': [],
  'book-circle-off': [],
  'book-off': [],
  'bookmark': ['record', 'video'],
  'bookmark-circle': [],
  'bookmark-circle-filled': [],
  'bookmark-circle-off': [],
  'bookmark-filled': [],
  'bookmark-filled-circle': [''],
  'bookmark-filled-circle-filled': [],
  'bookmark-filled-circle-off': [],
  'bookmark-filled-off': [],
  'bookmark-off': [],
  'briefcase': ['computer', 'desktop', 'screen'],
  'briefcase-circle': [],
  'briefcase-circle-filled': [],
  'briefcase-circle-off': [],
  'briefcase-off': [],
  'building': ['photography', 'shutter', 'picture'],
  'building-circle': [],
  'building-circle-filled': [],
  'building-circle-off': [],
  'building-off': [],
  'bulletin-notice': ['pdf'],
  'bulletin-notice-circle': [],
  'bulletin-notice-circle-filled': [],
  'bulletin-notice-circle-off': [],
  'bulletin-notice-off': [],
  'calculator': ['iphone', 'mobile-phone', 'cell-phone', 'gsm'],
  'calculator-circle': [],
  'calculator-circle-filled': [],
  'calculator-circle-off': [],
  'calculator-off': [],
  'calendar': ['iphone', 'mobile-phone', 'cell-phone', 'gsm'],
  'calendar-circle': [],
  'calendar-circle-filled': [],
  'calendar-circle-off': [],
  'calendar-off': [],
  'camera': ['iphone', 'mobile-phone', 'cell-phone', 'gsm'],
  'camera-circle': [],
  'camera-circle-filled': [],
  'camera-circle-off': [],
  'camera-off': [],
  'can': [''],
  'can-circle': [],
  'can-circle-filled': [],
  'can-circle-off': [],
  'can-off': [],
  'car': ['tv', 'telly'],
  'car-circle': [],
  'car-circle-filled': [],
  'car-circle-off': [],
  'car-off': [],
  'cart': ['tv', 'telly'],
  'cart-circle': [],
  'cart-circle-filled': [],
  'cart-circle-off': [],
  'cart-off': [],
  'cellphone-eye': [''],
  'cellphone-eye-circle': [],
  'cellphone-eye-circle-filled': [],
  'cellphone-eye-circle-off': [],
  'cellphone-eye-off': [],
  'cellphone-loop': [''],
  'cellphone-loop-circle': [],
  'cellphone-loop-circle-filled': [],
  'cellphone-loop-circle-off': [],
  'cellphone-loop-off': [],
  'chain': [''],
  'chain-circle': [],
  'chain-circle-filled': [],
  'chain-circle-off': [],
  'chain-off': [],
  'checkmark': [''],
  'checkmark-circle': [],
  'checkmark-circle-filled': [],
  'checkmark-circle-off': [],
  'checkmark-filled': [],
  'checkmark-filled-circle': [''],
  'checkmark-filled-circle-filled': [],
  'checkmark-filled-circle-off': [],
  'checkmark-filled-off': [],
  'checkmark-off': [],
  'checkmark-outlined': [''],
  'checkmark-outlined-circle': [],
  'checkmark-outlined-circle-filled': [],
  'checkmark-outlined-circle-off': [],
  'checkmark-outlined-off': [],
  'circle': [''],
  'circle-big': [],
  'circle-big-circle': [],
  'circle-big-circle-filled': [],
  'circle-big-circle-off': [],
  'circle-big-filled': ['pepsi', 'soft-drink', 'fizzy', 'cola', 'cold-drink', 'refresher', 'juice'],
  'circle-big-filled-circle': [],
  'circle-big-filled-circle-filled': [],
  'circle-big-filled-circle-off': [],
  'circle-big-filled-off': [],
  'circle-big-off': ['alcohol', 'tropical'],
  'circle-circle': [],
  'circle-circle-filled': [],
  'circle-circle-off': [],
  'circle-filled': [],
  'circle-filled-circle': ['coffee', 'hot-drink'],
  'circle-filled-circle-filled': [],
  'circle-filled-circle-off': [],
  'circle-filled-off': [],
  'circle-off': [],
  'clapperboard': ['fast-food'],
  'clapperboard-circle': [],
  'clapperboard-circle-filled': [],
  'clapperboard-circle-off': [],
  'clapperboard-off': [],
  'clipboard': ['eat', 'cutlery'],
  'clipboard-check': [],
  'clipboard-check-circle': [],
  'clipboard-check-circle-filled': [],
  'clipboard-check-circle-off': [],
  'clipboard-check-circled': ['cold-drink', 'refresher', 'juice'],
  'clipboard-check-circled-circle': [],
  'clipboard-check-circled-circle-filled': [],
  'clipboard-check-circled-circle-off': [],
  'clipboard-check-circled-off': [],
  'clipboard-check-off': ['hold', 'take', 'move', 'drag'],
  'clipboard-circle': [],
  'clipboard-circle-filled': [],
  'clipboard-circle-off': [],
  'clipboard-off': [],
  'clock': ['hello', 'greeting', 'salutation', 'raise-hand'],
  'clock-circle': [],
  'clock-circle-filled': [],
  'clock-circle-off': [],
  'clock-off': [],
  'cloud': ['direction', 'extend', 'finger', 'thumb', 'touch'],
  'cloud-circle': [],
  'cloud-circle-filled': [],
  'cloud-circle-off': [],
  'cloud-down': [],
  'cloud-down-circle': ['direction', 'extend', 'finger', 'touch'],
  'cloud-down-circle-filled': [],
  'cloud-down-circle-off': [],
  'cloud-down-off': [],
  'cloud-off': [],
  'cloud-up': ['vote', 'applause'],
  'cloud-up-circle': [],
  'cloud-up-circle-filled': [],
  'cloud-up-circle-off': [],
  'cloud-up-off': [],
  'coctail': ['vote', 'applause'],
  'coctail-circle': [],
  'coctail-circle-filled': [],
  'coctail-circle-off': [],
  'coctail-off': [],
  'code': ['grasp', 'greeting', 'touch', 'agreement', 'deal', 'pact', 'arrangement', 'business', 'friendship'],
  'code-circle': [],
  'code-circle-filled': [],
  'code-circle-off': [],
  'code-off': [],
  'coins': ['handbag', 'shoulder-bag', 'container', 'luggage', 'travel', 'work'],
  'coins-circle': [],
  'coins-circle-filled': [],
  'coins-circle-off': [],
  'coins-off': [],
  'color-picker': ['dumb-slate', 'filmmaking', 'video-production', 'scenes', 'takes', 'clapboard', 'clapstick', 'marker', 'slate-board', 'sync-slate', 'action', 'filming'],
  'color-picker-circle': [],
  'color-picker-circle-filled': [],
  'color-picker-circle-off': [],
  'color-picker-off': [],
  'comet': ['master-card', 'visa', 'cashless', 'payment', 'checkout'],
  'comet-circle': [],
  'comet-circle-filled': [],
  'comet-circle-off': [],
  'comet-off': [],
  'contract': ['coronet', 'diadem', 'tiara', 'circlet', 'title', 'award', 'accolade', 'honor', 'honour', 'distinction', 'glory', 'kudos', 'trophy', 'cup', 'medal', 'monarch', 'sovereign', 'king', 'queen', 'emperor', 'empress'],
  'contract-circle': [],
  'contract-circle-filled': [],
  'contract-circle-off': [],
  'contract-off': [],
  'controller': ['one-piece', 'clothing', 'gown', 'frock', 'garment'],
  'controller-circle': [],
  'controller-circle-filled': [],
  'controller-circle-off': [],
  'controller-off': [],
  'countdown': ['directors-chair', 'seat', 'photo-shoot', 'modelling', 'filming'],
  'countdown-circle': [],
  'countdown-circle-filled': [],
  'countdown-circle-off': [],
  'countdown-off': [],
  'credit-card': ['id', 'papers', 'identity', 'bona fides', 'credentials', 'id-card', 'pass', 'badge', 'warrant', 'licence', 'permit', 'passport', 'proof-of-identity', 'certificate', 'diploma'],
  'credit-card-circle': [],
  'credit-card-circle-filled': [],
  'credit-card-circle-off': [],
  'credit-card-off': [],
  'crown': ['attraction', 'repel', 'repulsion'],
  'crown-circle': [],
  'crown-circle-filled': [],
  'crown-circle-off': [],
  'crown-off': [],
  'cup': ['public-speaker', 'speech', 'lecture', 'yell', 'shout', 'announce', 'broadcast', 'proclaim', 'disclose'],
  'cup-circle': [],
  'cup-circle-filled': [],
  'cup-circle-off': [],
  'cup-off': [],
  'cv': ['photograph', 'picture', 'shot', 'snap', 'image', 'camera-roll'],
  'cv-circle': [],
  'cv-circle-filled': [],
  'cv-circle-off': [],
  'cv-off': [],
  'database': ['medicine', 'capsule', 'pellet', 'doctor', 'sick', 'disease', 'cure', 'drugs'],
  'database-circle': [],
  'database-circle-filled': [],
  'database-circle-off': [],
  'database-off': [],
  'division': ['lamp', 'beacon', 'photo-shoot', 'modelling', 'filming'],
  'division-circle': [],
  'division-circle-filled': [],
  'division-circle-off': [],
  'division-off': [],
  'dollar': ['lamp', 'beacon', 'photo-shoot', 'modelling', 'filming'],
  'dollar-circle': [],
  'dollar-circle-filled': [],
  'dollar-circle-off': [],
  'dollar-off': [],
  'dots-x': ['hypodermic', 'injection', 'vaccine', 'vaccination', 'doctor', 'sick', 'disease', 'cure', 'drugs'],
  'dots-x-circle': [],
  'dots-x-circle-filled': [],
  'dots-x-circle-off': [],
  'dots-x-off': [],
  'dots-y': ['clothing'],
  'dots-y-circle': [],
  'dots-y-circle-filled': [],
  'dots-y-circle-off': [],
  'dots-y-off': [],
  'down-left': ['pass', 'coupon', 'voucher', 'slip', 'card', 'fine', 'label', 'tag', 'sticker', 'tally', 'tab'],
  'down-left-circle': [],
  'down-left-circle-filled': [],
  'down-left-circle-off': [],
  'down-left-off': [],
  'down-up': ['cup', 'medal', 'prize', 'award', 'accolade', 'honour', 'distinction', 'glory', 'kudos', 'holy-grail'],
  'down-up-circle': [],
  'down-up-circle-filled': [],
  'down-up-circle-off': [],
  'down-up-off': [],
  'dress': ['parasol', 'rain'],
  'dress-circle': [],
  'dress-circle-filled': [],
  'dress-circle-off': [],
  'dress-off': [],
  'duplicate': ['read', 'bookmark'],
  'duplicate-circle': [],
  'duplicate-circle-filled': [],
  'duplicate-circle-off': [],
  'duplicate-off': [],
  'earth-americas': ['shopping', 'payout', 'commerce', 'transaction', 'buy', 'purchase'],
  'earth-americas-circle': [],
  'earth-americas-circle-filled': [],
  'earth-americas-circle-off': [],
  'earth-americas-off': [],
  'earth-asia': ['video-game', 'console'],
  'earth-asia-circle': [],
  'earth-asia-circle-filled': [],
  'earth-asia-circle-off': [],
  'earth-asia-off': [],
  'earth-europe': ['picture', 'movie', 'roll', 'feature', 'tv', 'television', 'programme', 'motion-picture', 'animation', 'flick', 'cinema'],
  'earth-europe-circle': [],
  'earth-europe-circle-filled': [],
  'earth-europe-circle-off': [],
  'earth-europe-off': [],
  'electricity': ['record', 'voice', 'radio', 'talent', 'idol', 'music', 'dance', 'singing', 'performance', 'live'],
  'electricity-circle': [],
  'electricity-circle-filled': [],
  'electricity-circle-off': [],
  'electricity-off': [],
  'enter': ['painter', 'art'],
  'enter-circle': [],
  'enter-circle-filled': [],
  'enter-circle-off': [],
  'enter-off': [],
  'equal': ['finance', 'financial-institution', 'money', 'cash', 'savings', 'investment', 'lending', 'loans', 'reserve', 'stock-market', 'payment', 'deposit'],
  'equal-circle': [],
  'equal-circle-filled': [],
  'equal-circle-off': [],
  'equal-off': [],
  'euro': ['office', 'sky-scraper', 'business', 'work', 'workplace', 'headquarters', 'enterprise', 'company', 'firm', 'bureau', 'agency', 'corporation'],
  'euro-circle': [],
  'euro-circle-filled': [],
  'euro-circle-off': [],
  'euro-off': [],
  'exclamation': ['banner', 'country', 'important', 'pin'],
  'exclamation-circle': [],
  'exclamation-circle-filled': [],
  'exclamation-circle-off': [],
  'exclamation-off': [],
  'expand': ['banner', 'country', 'important', 'pin'],
  'expand-circle': [],
  'expand-circle-filled': [],
  'expand-circle-off': [],
  'expand-off': [],
  'eye': ['doctor', 'clinic', 'medical-centre', 'institution', 'health', 'infirmary', 'nursing-home'],
  'eye-circle': [],
  'eye-circle-filled': [],
  'eye-circle-off': [],
  'eye-closed': [],
  'eye-closed-circle': ['home', 'residence'],
  'eye-closed-circle-filled': [],
  'eye-closed-circle-off': [],
  'eye-closed-off': [],
  'eye-frame': [],
  'eye-frame-circle': ['web', 'cyber', 'remote'],
  'eye-frame-circle-filled': [],
  'eye-frame-circle-off': [],
  'eye-frame-off': [],
  'eye-off': [],
  'face-frowning': ['location', 'directions'],
  'face-frowning-circle': [],
  'face-frowning-circle-filled': [],
  'face-frowning-circle-off': [],
  'face-frowning-off': [],
  'face-grinning': ['backdrop', 'photo-shoot', 'modelling', 'filming'],
  'face-grinning-circle': [],
  'face-grinning-circle-filled': [],
  'face-grinning-circle-off': [],
  'face-grinning-off': [],
  'face-smiling': ['location-marker', 'pin', 'position', 'map', 'here', 'where'],
  'face-smiling-circle': [],
  'face-smiling-circle-filled': [],
  'face-smiling-circle-off': [],
  'face-smiling-off': [],
  'fast-forward': ['photo-shoot', 'modelling', 'filming'],
  'fast-forward-circle': [],
  'fast-forward-circle-filled': [],
  'fast-forward-circle-off': [],
  'fast-forward-off': [],
  'file': [],
  'file-circle': [],
  'file-circle-filled': [],
  'file-circle-off': [],
  'file-loop': [],
  'file-loop-circle': [],
  'file-loop-circle-filled': [],
  'file-loop-circle-off': [],
  'file-loop-off': [],
  'file-off': [],
  'film-frame': ['oceania'],
  'film-frame-circle': [],
  'film-frame-circle-filled': [],
  'film-frame-circle-off': [],
  'film-frame-off': [],
  'fire': ['africa', 'middle-east'],
  'fire-circle': [],
  'fire-circle-filled': [],
  'fire-circle-off': [],
  'fire-off': [],
  'flag': ['thunder', 'lightning'],
  'flag-circle': [],
  'flag-circle-filled': [],
  'flag-circle-off': [],
  'flag-off': [],
  'flag-straight': ['inferno', 'ablaze', 'combustion', 'flames', 'heat', 'warmth', 'ignite', 'burn', 'fiery', 'popular', 'trending', 'attention', 'important', 'dangerous'],
  'flag-straight-circle': [],
  'flag-straight-circle-filled': [],
  'flag-straight-circle-off': [],
  'flag-straight-off': [],
  'floppy-disk': ['daisy'],
  'floppy-disk-circle': [],
  'floppy-disk-circle-filled': [],
  'floppy-disk-circle-off': [],
  'floppy-disk-off': [],
  'flower': ['tulip'],
  'flower-bud': [],
  'flower-bud-circle': [],
  'flower-bud-circle-filled': [],
  'flower-bud-circle-off': [],
  'flower-bud-off': [''],
  'flower-circle': [],
  'flower-circle-filled': [],
  'flower-circle-off': [],
  'flower-off': [],
  'folder': ['dark-mode', 'night', 'lights-out'],
  'folder-circle': [],
  'folder-circle-filled': [],
  'folder-circle-off': [],
  'folder-off': [],
  'folding-stool': [],
  'folding-stool-circle': [],
  'folding-stool-circle-filled': [],
  'folding-stool-circle-off': [],
  'folding-stool-off': [],
  'gear': [],
  'gear-circle': [],
  'gear-circle-filled': [],
  'gear-circle-off': [],
  'gear-off': [],
  'gift': [''],
  'gift-circle': [],
  'gift-circle-filled': [],
  'gift-circle-off': [],
  'gift-off': [],
  'grab-handle': ['favourite', 'favorite', 'rate', 'rating', 'score', 'flag'],
  'grab-handle-circle': [],
  'grab-handle-circle-filled': [],
  'grab-handle-circle-off': [],
  'grab-handle-off': [],
  'grid': ['favourite', 'favorite', 'rate', 'rating', 'score', 'flag'],
  'grid-circle': [],
  'grid-circle-filled': [],
  'grid-circle-off': [],
  'grid-off': [],
  'hamburger': ['sparkle', 'twinkle', 'shine', 'new', 'shiny'],
  'hamburger-circle': [],
  'hamburger-circle-filled': [],
  'hamburger-circle-off': [],
  'hamburger-off': [],
  'hammer-claw': ['light-mode', 'day', 'lights-on', 'brightness'],
  'hammer-claw-circle': [],
  'hammer-claw-circle-filled': [],
  'hammer-claw-circle-off': [],
  'hammer-claw-off': [],
  'hammer-sledge': [''],
  'hammer-sledge-circle': [],
  'hammer-sledge-circle-filled': [],
  'hammer-sledge-circle-off': [],
  'hammer-sledge-off': [],
  'hand-grab': ['aqua', 'liquid', 'drip', 'sprinkle', 'wet', 'damp', 'moist', 'spray', 'soak', 'splash', 'dilute'],
  'hand-grab-circle': [],
  'hand-grab-circle-filled': [],
  'hand-grab-circle-off': [],
  'hand-grab-off': [],
  'hand-open': ['bullet', 'ball'],
  'hand-open-circle': [],
  'hand-open-circle-filled': [],
  'hand-open-circle-off': [],
  'hand-open-off': [],
  'hand-point': ['bullet', 'ball'],
  'hand-point-circle': [],
  'hand-point-circle-filled': [],
  'hand-point-circle-off': [],
  'hand-point-off': [],
  'hand-point-open': ['bullet', 'ball'],
  'hand-point-open-circle': [],
  'hand-point-open-circle-filled': [],
  'hand-point-open-circle-off': [],
  'hand-point-open-off': [],
  'hands-clapping': ['bullet', 'ball'],
  'hands-clapping-checkmark': [],
  'hands-clapping-checkmark-circle': [],
  'hands-clapping-checkmark-circle-filled': [],
  'hands-clapping-checkmark-circle-off': [],
  'hands-clapping-checkmark-off': ['divide'],
  'hands-clapping-circle': [],
  'hands-clapping-circle-filled': [],
  'hands-clapping-circle-off': [],
  'hands-clapping-off': [],
  'handshake': ['is'],
  'handshake-circle': [],
  'handshake-circle-filled': [],
  'handshake-circle-off': [],
  'handshake-off': [],
  'hash': ['bang', 'exclamation-mark', 'exclamation-point', 'shriek', 'pling', 'note-of-admiration', 'warning', 'danger', 'error'],
  'hash-circle': [],
  'hash-circle-filled': [],
  'hash-circle-off': [],
  'hash-off': [],
  'headphone': ['information', 'help', 'hint', 'guide', 'tooltip'],
  'headphone-circle': [],
  'headphone-circle-filled': [],
  'headphone-circle-off': [],
  'headphone-off': [],
  'heart': ['slash', 'slant', 'backslash'],
  'heart-circle': [],
  'heart-circle-filled': [],
  'heart-circle-off': [],
  'heart-filled': [],
  'heart-filled-circle': ['slash', 'slant'],
  'heart-filled-circle-filled': [],
  'heart-filled-circle-off': [],
  'heart-filled-off': [],
  'heart-off': [],
  'hospital': ['dash', 'hyphen', 'bar', 'horizontal'],
  'hospital-circle': [],
  'hospital-circle-filled': [],
  'hospital-circle-off': [],
  'hospital-off': [],
  'hourglass': ['pipe', 'vertical'],
  'hourglass-circle': [],
  'hourglass-circle-filled': [],
  'hourglass-circle-off': [],
  'hourglass-off': [],
  'house': ['dash', 'hyphen', 'line'],
  'house-circle': [],
  'house-circle-filled': [],
  'house-circle-off': [],
  'house-off': [],
  'identification': ['cross', 'add', 'new'],
  'identification-circle': [],
  'identification-circle-filled': [],
  'identification-circle-off': [],
  'identification-off': [],
  'info': ['inquiry', 'query', 'interrogate', 'doubt', 'quiz', 'help', 'hint', 'tooltip'],
  'info-circle': [],
  'info-circle-filled': [],
  'info-circle-off': [],
  'info-off': [],
  'internet': [],
  'internet-circle': [],
  'internet-circle-filled': [],
  'internet-circle-off': [],
  'internet-off': [],
  'key': [],
  'key-circle': [],
  'key-circle-filled': [],
  'key-circle-off': [],
  'key-off': [],
  'keyboard': ['cross', 'x', 'wrong', 'close', 'stop'],
  'keyboard-circle': [],
  'keyboard-circle-filled': [],
  'keyboard-circle-off': [],
  'keyboard-off': [],
  'knive-fork': ['arrow-down'],
  'knive-fork-circle': [],
  'knive-fork-circle-filled': [],
  'knive-fork-circle-off': [],
  'knive-fork-off': [],
  'label': ['arrow-down'],
  'label-circle': [],
  'label-circle-filled': [],
  'label-circle-off': [],
  'label-off': [],
  'leaf': ['arrow-left'],
  'leaf-circle': [],
  'leaf-circle-filled': [],
  'leaf-circle-off': [],
  'leaf-off': [],
  'leave': ['arrow-left'],
  'leave-circle': [],
  'leave-circle-filled': [],
  'leave-circle-off': [],
  'leave-off': [],
  'letter': ['arrow-right'],
  'letter-circle': [],
  'letter-circle-filled': [],
  'letter-circle-off': [],
  'letter-off': [],
  'letter-open': ['arrow-right'],
  'letter-open-circle': [],
  'letter-open-circle-filled': [],
  'letter-open-circle-off': [],
  'letter-open-off': [],
  'line-slant-down': ['arrow-up'],
  'line-slant-down-circle': [],
  'line-slant-down-circle-filled': [],
  'line-slant-down-circle-off': [],
  'line-slant-down-off': [],
  'line-slant-up': ['arrow-up'],
  'line-slant-up-circle': [],
  'line-slant-up-circle-filled': [],
  'line-slant-up-circle-off': [],
  'line-slant-up-off': [],
  'line-x': ['life-history', 'biography', 'details', 'curriculum-vitae', 'entry', 'participation', 'candidate', 'applicant', 'submission', 'submit', 'apply', 'enter', 'interview'],
  'line-x-circle': [],
  'line-x-circle-filled': [],
  'line-x-circle-off': [],
  'line-x-off': [],
  'line-y': ['emoji', 'emoticon', 'smiley'],
  'line-y-circle': [],
  'line-y-circle-filled': [],
  'line-y-circle-off': [],
  'line-y-off': [],
  'list': ['emoji', 'emoticon', 'smiley'],
  'list-circle': [],
  'list-circle-filled': [],
  'list-circle-off': [],
  'list-off': [],
  'lock-closed': ['emoji', 'emoticon', 'smiley'],
  'lock-closed-circle': [],
  'lock-closed-circle-filled': [],
  'lock-closed-circle-off': [],
  'lock-closed-off': [],
  'lock-open': ['present', 'surprise', 'give'],
  'lock-open-circle': [],
  'lock-open-circle-filled': [],
  'lock-open-circle-off': [],
  'lock-open-off': [],
  'loop': ['love', 'like', 'favourite', 'favorite', 'relationship', 'emotion', 'feeling', 'affection'],
  'loop-circle': [],
  'loop-circle-filled': [],
  'loop-circle-off': [],
  'loop-minus': [],
  'loop-minus-circle': ['love', 'like', 'favourite', 'favorite', 'relationship', 'emotion', 'feeling', 'affection'],
  'loop-minus-circle-filled': [],
  'loop-minus-circle-off': [],
  'loop-minus-off': [],
  'loop-off': [],
  'loop-plus': ['offered', 'offer-letter', 'invitation', 'message', 'written', 'communication', 'note', 'report', 'correspondence', 'information', 'intelligence', 'mail', 'post'],
  'loop-plus-circle': [],
  'loop-plus-circle-filled': [],
  'loop-plus-circle-off': [],
  'loop-plus-off': [],
  'magnet': ['email', 'post', 'inbox'],
  'magnet-circle': [],
  'magnet-circle-filled': [],
  'magnet-circle-off': [],
  'magnet-off': [],
  'map': ['email', 'paper-plane'],
  'map-circle': [],
  'map-circle-filled': [],
  'map-circle-off': [],
  'map-off': [],
  'megaphone': ['3-persons', '3-people', 'group', 'following', 'crowd', 'band', 'gathering', 'company', 'assembly', 'association', 'club', 'society', 'guild', 'league', 'union', 'mass', 'triplet', 'accounts'],
  'megaphone-circle': [],
  'megaphone-circle-filled': [],
  'megaphone-circle-off': [],
  'megaphone-off': [],
  'menu': ['added', 'friends', 'know', 'following'],
  'menu-circle': [],
  'menu-circle-filled': [],
  'menu-circle-off': [],
  'menu-off': [],
  'microphone': ['friend', 'plus', 'cross', 'add', 'new', 'follow'],
  'microphone-circle': [],
  'microphone-circle-filled': [],
  'microphone-circle-off': [],
  'microphone-handheld': [],
  'microphone-handheld-circle': ['human', 'man', 'someone', 'unknown', 'identity', 'profile', 'you', 'account'],
  'microphone-handheld-circle-filled': [],
  'microphone-handheld-circle-off': [],
  'microphone-handheld-off': [],
  'microphone-off': [],
  'minus': ['human', 'man', 'someone', 'unknown', 'identity', 'profile', 'you', '2-persons', '2-people', 'pair', 'partnership', 'couple', 'duo', 'duplet', 'accounts'],
  'minus-circle': [],
  'minus-circle-filled': [],
  'minus-circle-off': [],
  'minus-off': [],
  'money-note': ['call', 'talk', 'telephone'],
  'money-note-circle': [],
  'money-note-circle-filled': [],
  'money-note-circle-off': [],
  'money-note-off': [],
  'monitor': ['question', 'ask', 'attention'],
  'monitor-circle': [],
  'monitor-circle-filled': [],
  'monitor-circle-off': [],
  'monitor-eye': [],
  'monitor-eye-circle': ['forward', 'connect'],
  'monitor-eye-circle-filled': [],
  'monitor-eye-circle-off': [],
  'monitor-eye-off': [],
  'monitor-loop': [],
  'monitor-loop-circle': ['forward', 'connect'],
  'monitor-loop-circle-filled': [],
  'monitor-loop-circle-off': [],
  'monitor-loop-off': [],
  'monitor-off': [],
  'moon': ['message', 'chat', 'say', 'typing'],
  'moon-circle': [],
  'moon-circle-filled': [],
  'moon-circle-off': [],
  'moon-off': [],
  'motorcycle': ['messages', 'chatting', 'saying', 'typing', 'group-chat'],
  'motorcycle-circle': [],
  'motorcycle-circle-filled': [],
  'motorcycle-circle-off': [],
  'motorcycle-off': [],
  'move-x': ['dislike', 'hate', 'vote', 'downvote', 'gesture', 'block'],
  'move-x-circle': [],
  'move-x-circle-filled': [],
  'move-x-circle-off': [],
  'move-x-off': [],
  'move-y': ['like', 'love', 'vote', 'upvote', 'gesture', 'favorite', 'favourite'],
  'move-y-circle': [],
  'move-y-circle-filled': [],
  'move-y-circle-off': [],
  'move-y-off': [],
  'music-note-double': ['notification', 'attention', 'alert'],
  'music-note-double-circle': [],
  'music-note-double-circle-filled': [],
  'music-note-double-circle-off': [],
  'music-note-double-off': [],
  'music-note-single': ['audio', 'media-controls', 'music'],
  'music-note-single-circle': [],
  'music-note-single-circle-filled': [],
  'music-note-single-circle-off': [],
  'music-note-single-off': [],
  'next-track': ['headset', 'earphone', 'music', 'listen', 'anc'],
  'next-track-circle': [],
  'next-track-circle-filled': [],
  'next-track-circle-off': [],
  'next-track-off': [],
  'no-entry': ['record', 'voice', 'radio'],
  'no-entry-circle': [],
  'no-entry-circle-filled': [],
  'no-entry-circle-off': [],
  'no-entry-off': [],
  'nut': ['score', 'solfege', 'song'],
  'nut-circle': [],
  'nut-circle-filled': [],
  'nut-circle-off': [],
  'nut-off': [],
  'open': ['score', 'solfege', 'song'],
  'open-circle': [],
  'open-circle-filled': [],
  'open-circle-off': [],
  'open-off': [],
  'paint-pallet': ['audio', 'media-controls', 'music'],
  'paint-pallet-circle': [],
  'paint-pallet-circle-filled': [],
  'paint-pallet-circle-off': [],
  'paint-pallet-off': [],
  'paper-plane': ['audio', 'media-controls', 'music'],
  'paper-plane-circle': [],
  'paper-plane-circle-filled': [],
  'paper-plane-circle-off': [],
  'paper-plane-off': [],
  'paperclip': ['audio', 'media-controls', 'music'],
  'paperclip-circle': [],
  'paperclip-circle-filled': [],
  'paperclip-circle-off': [],
  'paperclip-off': [],
  'pause': ['audio', 'media-controls', 'music'],
  'pause-circle': [],
  'pause-circle-filled': [],
  'pause-circle-off': [],
  'pause-off': [],
  'pen': ['music', 'listening', 'podcast'],
  'pen-circle': [],
  'pen-circle-filled': [],
  'pen-circle-off': [],
  'pen-off': [],
  'people': ['audio', 'media-controls', 'music'],
  'people-circle': [],
  'people-circle-filled': [],
  'people-circle-off': [],
  'people-off': [],
  'person': ['audio', 'media-controls', 'music'],
  'person-checkmark': [],
  'person-checkmark-circle': [],
  'person-checkmark-circle-filled': [],
  'person-checkmark-circle-off': [],
  'person-checkmark-off': ['audio', 'media-controls', 'music'],
  'person-circle': [],
  'person-circle-filled': [],
  'person-circle-off': [],
  'person-off': [],
  'person-plus': ['high-volume', 'loud'],
  'person-plus-circle': [],
  'person-plus-circle-filled': [],
  'person-plus-circle-off': [],
  'person-plus-off': [],
  'persons': ['low-volume', 'quiet'],
  'persons-circle': [],
  'persons-circle-filled': [],
  'persons-circle-off': [],
  'persons-off': [],
  'peso': ['alarm-clock', 'siren', 'bell', 'wake-up', 'early', 'timer'],
  'peso-circle': [],
  'peso-circle-filled': [],
  'peso-circle-off': [],
  'peso-off': [],
  'phone': ['date', 'when', 'event', 'deadline'],
  'phone-circle': [],
  'phone-circle-filled': [],
  'phone-circle-off': [],
  'phone-off': [],
  'photo': ['time', 'timer', 'countdown', 'deadline', 'hour', 'watch'],
  'photo-camera': [],
  'photo-camera-circle': [],
  'photo-camera-circle-filled': [],
  'photo-camera-circle-off': [],
  'photo-camera-off': ['timer', 'clock', 'stopwatch'],
  'photo-circle': [],
  'photo-circle-filled': [],
  'photo-circle-off': [],
  'photo-off': [],
  'photo-studio': ['sandglass', 'countdown', 'stopwatch', 'clock'],
  'photo-studio-circle': [],
  'photo-studio-circle-filled': [],
  'photo-studio-circle-off': [],
  'photo-studio-off': [],
  'pill': ['turn-back-time', 'go-back', 'previous'],
  'pill-circle': [],
  'pill-circle-filled': [],
  'pill-circle-off': [],
  'pill-off': [],
  'pin': ['alarm', 'timer', 'clock', 'countdown', 'race', 'track', 'pedometer'],
  'pin-circle': [],
  'pin-circle-filled': [],
  'pin-circle-off': [],
  'pin-off': [],
  'pinpoint': ['wristwatch', 'time', 'clock', 'pocket-watch'],
  'pinpoint-circle': [],
  'pinpoint-circle-filled': [],
  'pinpoint-circle-off': [],
  'pinpoint-off': [],
  'planet': ['flag', 'clip'],
  'planet-circle': [],
  'planet-circle-filled': [],
  'planet-circle-off': [],
  'planet-off': [],
  'planet-ring': ['flag', 'clip'],
  'planet-ring-circle': [],
  'planet-ring-circle-filled': [],
  'planet-ring-circle-off': [],
  'planet-ring-off': [],
  'play': [''],
  'play-circle': [],
  'play-circle-filled': [],
  'play-circle-off': [],
  'play-off': [],
  'plus': ['copy', 'duplicate', 'paste'],
  'plus-circle': [],
  'plus-circle-filled': [],
  'plus-circle-off': [],
  'plus-off': [],
  'power': ['copy', 'duplicate', 'paste'],
  'power-circle': [],
  'power-circle-filled': [],
  'power-circle-off': [],
  'power-off': [],
  'previous-track': ['copy', 'duplicate', 'paste'],
  'previous-track-circle': [],
  'previous-track-circle-filled': [],
  'previous-track-circle-off': [],
  'previous-track-off': [],
  'printer': [],
  'printer-circle': [],
  'printer-circle-filled': [],
  'printer-circle-off': [],
  'printer-off': [],
  'qr-code': ['save'],
  'qr-code-circle': [],
  'qr-code-circle-filled': [],
  'qr-code-circle-off': [],
  'qr-code-off': [],
  'question': ['settings', 'cogwheel', 'configuration', 'mechanical', 'machinery'],
  'question-circle': [],
  'question-circle-filled': [],
  'question-circle-off': [],
  'question-off': [],
  'radio': [],
  'radio-circle': [],
  'radio-circle-filled': [],
  'radio-circle-off': [],
  'radio-off': [],
  'raise-hand': [''],
  'raise-hand-circle': [],
  'raise-hand-circle-filled': [],
  'raise-hand-circle-off': [],
  'raise-hand-off': [],
  'repeat': ['lock', 'unlock', 'encrypt', 'decrypt', 'safe', 'secret', 'solution', 'answer'],
  'repeat-circle': [],
  'repeat-circle-filled': [],
  'repeat-circle-off': [],
  'repeat-off': [],
  'rewind': ['tag', 'flag', 'ticket', 'badge'],
  'rewind-circle': [],
  'rewind-circle-filled': [],
  'rewind-circle-off': [],
  'rewind-off': [],
  'rewind-time': ['lock', 'encrypt'],
  'rewind-time-circle': [],
  'rewind-time-circle-filled': [],
  'rewind-time-circle-off': [],
  'rewind-time-off': [],
  'ruler': ['unlock', 'decrypt'],
  'ruler-circle': [],
  'ruler-circle-filled': [],
  'ruler-circle-off': [],
  'ruler-off': [],
  'scissors': [''],
  'scissors-circle': [],
  'scissors-circle-filled': [],
  'scissors-circle-off': [],
  'scissors-off': [],
  'seedling': ['attachment'],
  'seedling-circle': [],
  'seedling-circle-filled': [],
  'seedling-circle-off': [],
  'seedling-off': [],
  'share-android': ['edit', 'write', 'pencil', 'draw', 'modify', 'update'],
  'share-android-circle': [],
  'share-android-circle-filled': [],
  'share-android-circle-off': [],
  'share-android-off': [],
  'share-ios': ['nail', 'peg', 'stick', 'attach', 'fix', 'keep'],
  'share-ios-circle': [],
  'share-ios-circle-filled': [],
  'share-ios-circle-off': [],
  'share-ios-off': [],
  'shield': [''],
  'shield-check': [],
  'shield-check-circle': [],
  'shield-check-circle-filled': [],
  'shield-check-circle-off': [],
  'shield-check-off': ['cut', 'hair', 'clippers', 'shears', 'trimmer', 'barber', 'stylist', 'beauty-parlor', 'coiffeuse', 'coiffeur'],
  'shield-checkered': [],
  'shield-checkered-circle': [],
  'shield-checkered-circle-filled': [],
  'shield-checkered-circle-off': [],
  'shield-checkered-off': ['delete', 'remove', 'dispense', 'trashcan', 'can', 'garbage'],
  'shield-circle': [],
  'shield-circle-filled': [],
  'shield-circle-off': [],
  'shield-off': [],
  'shuffle': ['hardware', 'fix', 'repair', 'bolt'],
  'shuffle-circle': [],
  'shuffle-circle-filled': [],
  'shuffle-circle-off': [],
  'shuffle-off': [],
  'sliders': ['aeroplane', 'fly', 'travel', 'vacation', 'trip', 'flight', 'airport'],
  'sliders-circle': [],
  'sliders-circle-filled': [],
  'sliders-circle-off': [],
  'sliders-off': [],
  'smartphone-cutout': ['bike'],
  'smartphone-cutout-circle': [],
  'smartphone-cutout-circle-filled': [],
  'smartphone-cutout-circle-off': [],
  'smartphone-cutout-off': [],
  'smartphone-home-button': ['automobile', 'drive'],
  'smartphone-home-button-circle': [],
  'smartphone-home-button-circle-filled': [],
  'smartphone-home-button-circle-off': [],
  'smartphone-home-button-off': [],
  'smartphone-notch': ['bike'],
  'smartphone-notch-circle': [],
  'smartphone-notch-circle-filled': [],
  'smartphone-notch-circle-off': [],
  'smartphone-notch-off': [],
  'soft-drink': ['cab'],
  'soft-drink-circle': [],
  'soft-drink-circle-filled': [],
  'soft-drink-circle-off': [],
  'soft-drink-off': [],
  'speaker-high': ['tube', 'metro'],
  'speaker-high-circle': [],
  'speaker-high-circle-filled': [],
  'speaker-high-circle-off': [],
  'speaker-high-off': [],
  'speaker-low': ['heavy-goods-vehicle', 'juggernaut', 'van', 'pickup', 'lorry', 'move', 'wares', 'deliver', 'haul', 'distribution', 'delivery'],
  'speaker-low-circle': [],
  'speaker-low-circle-filled': [],
  'speaker-low-circle-off': [],
  'speaker-low-off': [],
  'square': [],
  'square-circle': [],
  'square-circle-filled': [],
  'square-circle-off': [],
  'square-filled': [],
  'square-filled-circle': ['preview', 'document', 'analysis', 'evaluation', 'assessment', 'examination', 'check', 'inspection', 'probe', 'audit', 'survey', 'browse'],
  'square-filled-circle-filled': [],
  'square-filled-circle-off': [],
  'square-filled-off': [],
  'square-off': [],
  'star': ['preview', 'document', 'analysis', 'evaluation', 'assessment', 'examination', 'check', 'inspection', 'probe', 'audit', 'survey', 'browse'],
  'star-circle': [],
  'star-circle-filled': [],
  'star-circle-off': [],
  'star-filled': [],
  'star-filled-circle': ['link', 'url', 'anchor', 'open', 'website', 'shackle', 'connect', 'bond', 'bind', 'joint', 'knot'],
  'star-filled-circle-filled': [],
  'star-filled-circle-off': [],
  'star-filled-off': [],
  'star-off': [],
  'stars': ['authorized', 'accredited', 'approved', 'validated', 'authenticated', 'authentic', 'certified', 'endorsed', 'documented', 'sanctioned', 'licensed', 'formal', 'recognized', 'authoritative', 'accepted', 'verified', 'legitimate', 'legal', 'lawful', 'valid', 'bona fide', 'proper', 'true', 'ex cathedra', 'si'],
  'stars-circle': [],
  'stars-circle-filled': [],
  'stars-circle-off': [],
  'stars-off': [],
  'stopwatch': ['official', 'authorized', 'accredited', 'approved', 'validated', 'authenticated', 'authentic', 'certified', 'endorsed', 'documented', 'sanctioned', 'licensed', 'formal', 'recognized', 'authoritative', 'accepted', 'verified', 'legitimate', 'legal', 'lawful', 'valid', 'bona fide', 'proper', 'true', 'ex'],
  'stopwatch-circle': [],
  'stopwatch-circle-filled': [],
  'stopwatch-circle-off': [],
  'stopwatch-off': [],
  'studio-backdrop': ['check', 'toggle', 'tick', 'ok', 'confirmed'],
  'studio-backdrop-circle': [],
  'studio-backdrop-circle-filled': [],
  'studio-backdrop-circle-off': [],
  'studio-backdrop-off': [],
  'studio-light-front': ['download', 'storage', 'retrieve', 'fetch', 'local', 'load'],
  'studio-light-front-circle': [],
  'studio-light-front-circle-filled': [],
  'studio-light-front-circle-off': [],
  'studio-light-front-off': [],
  'studio-light-side': ['upload', 'storage', 'save'],
  'studio-light-side-circle': [],
  'studio-light-side-circle-filled': [],
  'studio-light-side-circle-off': [],
  'studio-light-side-off': [],
  'sun': ['upload', 'online', 'storage', 'save'],
  'sun-circle': [],
  'sun-circle-filled': [],
  'sun-circle-off': [],
  'sun-off': [],
  'sword': ['programming', 'coding', 'html', 'xml'],
  'sword-circle': [],
  'sword-circle-filled': [],
  'sword-circle-off': [],
  'sword-off': [],
  'sword-shield': ['db'],
  'sword-shield-circle': [],
  'sword-shield-circle-filled': [],
  'sword-shield-circle-off': [],
  'sword-shield-off': [],
  'swords': ['dots-horizontal', 'more', 'details', 'menu'],
  'swords-circle': [],
  'swords-circle-filled': [],
  'swords-circle-off': [],
  'swords-off': [],
  'syringe': ['dots-vertical', 'more', 'details', 'menu'],
  'syringe-circle': [],
  'syringe-circle-filled': [],
  'syringe-circle-off': [],
  'syringe-off': [],
  't-shirt': ['copy'],
  't-shirt-circle': [],
  't-shirt-circle-filled': [],
  't-shirt-circle-off': [],
  't-shirt-off': [],
  'tablet': ['login', 'log-in', 'signin', 'sign-in', 'join', 'embark', 'start', 'begin', 'into', 'enlist', 'entrance', 'submit', 'advance', 'register'],
  'tablet-circle': [],
  'tablet-circle-filled': [],
  'tablet-circle-off': [],
  'tablet-off': [],
  'taxi': ['password-hidden', 'invisible', 'hide', 'secret', 'asleep'],
  'taxi-circle': [],
  'taxi-circle-filled': [],
  'taxi-circle-off': [],
  'taxi-off': [],
  'television': ['preview', 'document', 'analysis', 'evaluation', 'assessment', 'examination', 'check', 'inspection', 'probe', 'audit', 'survey', 'browse'],
  'television-circle': [],
  'television-circle-filled': [],
  'television-circle-off': [],
  'television-off': [],
  'television-play': ['password-visible', 'see', 'watch', 'awake'],
  'television-play-circle': [],
  'television-play-circle-filled': [],
  'television-play-circle-off': [],
  'television-play-off': [],
  'text-bubble': ['preview', 'document', 'analysis', 'evaluation', 'assessment', 'examination', 'check', 'inspection', 'probe', 'audit', 'survey', 'browse'],
  'text-bubble-circle': [],
  'text-bubble-circle-filled': [],
  'text-bubble-circle-off': [],
  'text-bubble-off': [],
  'text-bubbles': ['document', 'record', 'note', 'data', 'archive'],
  'text-bubbles-circle': [],
  'text-bubbles-circle-filled': [],
  'text-bubbles-circle-off': [],
  'text-bubbles-off': [],
  'thumbs-down': ['container', 'binder', 'files', 'archive', 'save', 'record', 'keep'],
  'thumbs-down-circle': [],
  'thumbs-down-circle-filled': [],
  'thumbs-down-circle-off': [],
  'thumbs-down-off': [],
  'thumbs-up': ['handle', 'move', 'drag'],
  'thumbs-up-circle': [],
  'thumbs-up-circle-filled': [],
  'thumbs-up-circle-off': [],
  'thumbs-up-off': [],
  'ticket': ['cards', 'table', 'list', 'to-do', 'todo', 'items', 'sort', 'organise', 'organize', 'tasks', 'sheet', 'entries', 'register', 'directory', 'catalogue', 'inventory', 'index', 'checklist', 'table'],
  'ticket-circle': [],
  'ticket-circle-filled': [],
  'ticket-circle-off': [],
  'ticket-off': [],
  'times': ['hashtag', 'tag', 'pound-key'],
  'times-circle': [],
  'times-circle-filled': [],
  'times-circle-off': [],
  'times-off': [],
  'train': ['logout', 'log-out', 'sign-out', 'signout', 'stop', 'depart', 'retire', 'withdraw', 'exit', 'abandon', 'quit', 'resign', 'retire', 'gone'],
  'train-circle': [],
  'train-circle-filled': [],
  'train-circle-off': [],
  'train-off': [],
  'trash': ['to-do', 'todo', 'items', 'sort', 'organise', 'organize', 'tasks', 'sheet', 'entries', 'register', 'directory', 'catalogue', 'inventory', 'index', 'checklist', 'table'],
  'trash-circle': [],
  'trash-circle-filled': [],
  'trash-circle-off': [],
  'trash-off': [],
  'tree': ['zoom-out', 'magnify-out', 'farther', 'further'],
  'tree-circle': [],
  'tree-circle-filled': [],
  'tree-circle-off': [],
  'tree-off': [],
  'triangle-down': ['zoom-in', 'magnify-in', 'closer'],
  'triangle-down-circle': [],
  'triangle-down-circle-filled': [],
  'triangle-down-circle-off': [],
  'triangle-down-filled': [],
  'triangle-down-filled-circle': ['zoom', 'magnify', 'detective'],
  'triangle-down-filled-circle-filled': [],
  'triangle-down-filled-circle-off': [],
  'triangle-down-filled-off': [],
  'triangle-down-off': [],
  'triangle-left': ['hamburger', 'list', 'align', 'text', 'show-more'],
  'triangle-left-circle': [],
  'triangle-left-circle-filled': [],
  'triangle-left-circle-off': [],
  'triangle-left-filled': [],
  'triangle-left-filled-circle': ['preview', 'document', 'analysis', 'evaluation', 'assessment', 'examination', 'check', 'inspection', 'probe', 'audit', 'survey', 'browse'],
  'triangle-left-filled-circle-filled': [],
  'triangle-left-filled-circle-off': [],
  'triangle-left-filled-off': [],
  'triangle-left-off': [],
  'triangle-right': ['preview', 'document', 'analysis', 'evaluation', 'assessment', 'examination', 'check', 'inspection', 'probe', 'audit', 'survey', 'browse'],
  'triangle-right-circle': [],
  'triangle-right-circle-filled': [],
  'triangle-right-circle-off': [],
  'triangle-right-filled': [],
  'triangle-right-filled-circle': [],
  'triangle-right-filled-circle-filled': [],
  'triangle-right-filled-circle-off': [],
  'triangle-right-filled-off': [],
  'triangle-right-off': [],
  'triangle-up': ['link', 'new-tab', 'external', 'go'],
  'triangle-up-circle': [],
  'triangle-up-circle-filled': [],
  'triangle-up-circle-off': [],
  'triangle-up-filled': [],
  'triangle-up-filled-circle': ['turn-off', 'shut-down'],
  'triangle-up-filled-circle-filled': [],
  'triangle-up-filled-circle-off': [],
  'triangle-up-filled-off': [],
  'triangle-up-off': [],
  'trophy': ['bar-code', 'barcode', 'scan'],
  'trophy-circle': [],
  'trophy-circle-filled': [],
  'trophy-circle-off': [],
  'trophy-off': [],
  'truck': ['settings', 'options', 'configuration', 'toggles', 'filters', 'knobs'],
  'truck-circle': [],
  'truck-circle-filled': [],
  'truck-circle-off': [],
  'truck-off': [],
  'umbrella': ['internet', 'reception', 'connection', 'sonic', 'waves'],
  'umbrella-circle': [],
  'umbrella-circle-filled': [],
  'umbrella-circle-off': [],
  'umbrella-off': [],
  'watch': ['security'],
  'watch-circle': [],
  'watch-circle-filled': [],
  'watch-circle-off': [],
  'watch-off': [],
  'water-drop': [''],
  'water-drop-circle': [],
  'water-drop-circle-filled': [],
  'water-drop-circle-off': [],
  'water-drop-off': [],
  'wifi': [''],
  'wifi-circle': [],
  'wifi-circle-filled': [],
  'wifi-circle-off': [],
  'wifi-off': [],
  'wrench': [''],
  'wrench-circle': [],
  'wrench-circle-filled': [],
  'wrench-circle-off': [],
  'wrench-off': [],
  'yen': [''],
  'yen-circle': [],
  'yen-circle-filled': [],
  'yen-circle-off': [],
  'yen-off': [],
  'yuan': [''],
  'yuan-circle': [],
  'yuan-circle-filled': [],
  'yuan-circle-off': [],
  'yuan-off': [],
}
