/** This file is to be manually edited. */

import { Pepicon } from '../types'

export const synonyms: { [name in Pepicon]: string[] } = {
  'airplane': ['aeroplane', 'fly', 'travel', 'vacation', 'trip'],
  'arrow-down': ['chevron-down'],
  'arrow-left': ['chevron-left'],
  'arrow-right': ['chevron-right'],
  'arrow-up': ['chevron-up'],
  'battery': ['charge'],
  'bell': ['notification'],
  'bell-off': ['no-notification', 'silent'],
  'bicycle': ['bike'],
  'bluetooth': [],
  'book': ['read', 'bookmark'],
  'bookmark': ['flag', 'clip'],
  'bookmark-filled': ['flag', 'clip'],
  'building': [
    'office',
    'sky-scraper',
    'business',
    'work',
    'workplace',
    'headquarters',
    'enterprise',
    'company',
    'firm',
    'bureau',
    'agency',
    'corporation',
  ],
  'calculator': ['calculate'],
  'calendar': ['date', 'when'],
  'camera': ['record', 'video'],
  'can': ['pepsi', 'soft-drink', 'fizzy', 'cola', 'cold-drink', 'refresher', 'juice'],
  'car': ['automobile', 'drive'],
  'cart': ['shopping', 'payout', 'commerce', 'transaction', 'buy', 'purchase'],
  'checkmark': ['check', 'toggle'],
  'circle': ['bullet', 'ball'],
  'circle-filled': ['bullet', 'ball'],
  'clipboard': ['copy'],
  'clock': ['time', 'timer', 'countdown'],
  'cloud': ['upload', 'online', 'storage', 'save'],
  'cloud-down': ['download', 'storage', 'retrieve', 'fetch', 'local', 'load'],
  'cloud-down-filled': ['download', 'storage', 'retrieve', 'fetch', 'local', 'load'],
  'cloud-filled': ['upload', 'online', 'storage', 'save'],
  'cloud-up': ['upload', 'storage', 'save'],
  'cloud-up-filled': ['upload', 'storage', 'save'],
  'coctail': ['alcohol', 'tropical'],
  'color-picker': [],
  'contract': ['shrink', 'close', 'zoom-out', 'minimize'],
  'controller': ['video-game', 'console'],
  'credit-card': ['master-card', 'visa', 'cashless', 'payment', 'checkout'],
  'cup': ['coffee', 'hot-drink'],
  'division': ['divide'],
  'dots-horizontal': ['more', 'details', 'menu'],
  'dots-vertical': ['more', 'details', 'menu'],
  'dress': ['one-piece', 'clothing', 'gown', 'frock', 'garment'],
  'duplicate': ['copy'],
  'electricity': ['thunder', 'lightning'],
  'exclamation-mark': ['warning', 'danger', 'note'],
  'exclamation-mark-filled': ['warning', 'danger', 'note'],
  'expand': ['fullscreen', 'open', 'zoom-in', 'maximize'],
  'eye': ['password-visible', 'see', 'watch', 'awake'],
  'eye-closed': ['password-hidden', 'invisible', 'hide', 'secret', 'asleep'],
  'eye-off': ['password-hidden', 'invisible', 'hide', 'secret', 'not-allowed', 'no-access'],
  'file': ['document', 'record', 'note', 'data', 'archive'],
  'film-frame': [
    'picture',
    'movie',
    'roll',
    'feature',
    'tv',
    'television',
    'programme',
    'motion-picture',
    'animation',
    'flick',
    'cinema',
  ],
  'flag': ['banner', 'country', 'important', 'pin'],
  'flower': ['tulip'],
  'flower-bud': ['daisy'],
  'folder': ['container', 'binder', 'files', 'archive', 'save', 'record', 'keep'],
  'gear': ['settings', 'cogwheel', 'configuration', 'mechanical', 'machinery'],
  'gift': ['present', 'surprise', 'give'],
  'grab': ['handle', 'move', 'drag'],
  'hamburger': ['fast-food'],
  'headphone': ['headset', 'earphone', 'music', 'listen', 'anc'],
  'heart': ['love', 'like'],
  'home': ['house', 'recidence'],
  'information': ['hint', 'guide'],
  'information-filled': ['hint', 'guide'],
  'internet': ['web', 'cyber', 'remote'],
  'key': ['lock', 'unlock', 'encrypt', 'decrypt', 'safe', 'secret', 'solution', 'answer'],
  'knive-fork': ['eat', 'cutlery'],
  'letter': ['email', 'post', 'inbox'],
  'location-marker': ['pin', 'position', 'map', 'here', 'where'],
  'location-marker-filled': ['pin', 'position', 'map', 'here', 'where'],
  'location-marker-off': ['pin', 'position', 'map', 'here', 'where'],
  'location-marker-off-filled': ['pin', 'position', 'map', 'here', 'where'],
  'lock-closed': ['lock', 'encrypt'],
  'lock-open': ['unlock', 'decrypt'],
  'loop': ['zoom', 'magnify', 'detective'],
  'loop-minus': ['zoom-out', 'magnify-out', 'farther', 'further'],
  'loop-plus': ['zoom-in', 'magnify-in', 'closer'],
  'map': ['location', 'directions'],
  'microphone': ['record', 'voice', 'radio'],
  'minus': ['dash', 'hyphen', 'line'],
  'monitor': ['computer', 'desktop', 'screen'],
  'monitor2': ['computer', 'desktop', 'screen'],
  'moon': ['dark-mode', 'night', 'lights-out'],
  'moon-filled': ['dark-mode', 'lights-out'],
  'motorcycle': ['bike'],
  'music-note-double': ['score'],
  'music-note-single': ['score'],
  'open': ['link', 'new-tab', 'external', 'go'],
  'paint-pallet': ['painter', 'art'],
  'pen': ['edit', 'write', 'pencil'],
  'person': ['human', 'man', 'someone', 'unknown', 'identity', 'profile', 'you'],
  'person-filled': ['human', 'man', 'someone', 'unknown', 'identity', 'profile', 'you'],
  'phone': ['call', 'talk'],
  'photo-camera': ['photography', 'shutter', 'picture'],
  'pill': ['medicine', 'capsule', 'pellet', 'doctor', 'sick', 'disease', 'cure', 'drugs'],
  'plus': ['cross'],
  'power': ['turn-off', 'shut-down'],
  'printer': ['pdf'],
  'refresh': ['reload', 'fetch', 'twist'],
  'reload': ['refresh', 'turn', 'start-over', 'back'],
  'scissors': [
    'cut',
    'hair',
    'clippers',
    'shears',
    'trimmer',
    'barber',
    'stylist',
    'beauty-parlor',
    'coiffeuse',
    'coiffeur',
  ],
  'send': ['email', 'paper-plane'],
  'share-android': ['forward', 'connect'],
  'share-ios': ['forward', 'connect'],
  'smartphone': ['iphone', 'mobile-phone', 'cell-phone', 'gsm'],
  'smartphone2': ['iphone', 'mobile-phone', 'cell-phone', 'gsm'],
  'soft-drink': ['cold-drink', 'refresher', 'juice'],
  'speaker-high': ['high-volume', 'loud'],
  'speaker-low': ['low-volume', 'quiet'],
  'speaker-off': ['no-volume', 'silent'],
  'square': [],
  'square-filled': [],
  'star': ['favourite', 'rate'],
  'sun': ['light-mode', 'day', 'lights-on', 'brightness'],
  'sun-filled': ['light-mode', 'lights-on', 'brightness'],
  'syringe': [
    'hypodermic',
    'injection',
    'vaccine',
    'vaccination',
    'doctor',
    'sick',
    'disease',
    'cure',
    'drugs',
  ],
  't-shirt': ['clothing'],
  'taxi': ['cab'],
  'television': ['tv', 'telly'],
  'text-bubble': ['message', 'chat', 'say'],
  'times': ['cross', 'x', 'wrong'],
  'tool': ['wrench', 'hardware', 'fix', 'repair', 'bolt'],
  'train': ['tube', 'metro'],
  'trash': ['delete', 'remove', 'dispense', 'trashcan', 'can', 'garbage'],
  'triangle-down': ['arrow-down'],
  'triangle-down-filled': ['arrow-down'],
  'triangle-left': ['arrow-left'],
  'triangle-left-filled': ['arrow-left'],
  'triangle-right': ['arrow-right'],
  'triangle-right-filled': ['arrow-right'],
  'triangle-up': ['arrow-up'],
  'triangle-up-filled': ['arrow-up'],
  'truck': [
    'heavy-goods-vehicle',
    'juggernaut',
    'van',
    'pickup',
    'lorry',
    'move',
    'wares',
    'deliver',
    'haul',
    'distribution',
    'delivery',
  ],
  'umbrella': ['parasol', 'rain'],
  'wifi': ['internet', 'reception', 'connection', 'sonic', 'waves'],
}
